### ISSUE TITLE
misleading versions

### ISSUE THREAD

**Issue by wyand** [nebula-plugins/nebula-kotlin-plugin#10]
With version 1.1.2-5 of the nebula plugin applied as follows:

    plugins {
        id 'nebula.kotlin' version '1.1.2-5' apply false
    }

my projects that `apply 'nebula.kotlin'` build with 1.1.2, instead of 1.1.2-5. I can repair this by including a specific kotlin version, but it feels clunky:

    plugins {
        id 'org.jetbrains.kotlin.jvm' version '1.1.2-5' apply false
        id 'nebula.kotlin' version '1.1.2-5' apply false
    }

Is this expected, a bug, or am I doing something wrong?

**Comment by DanielThomas** [comment]
It's a bug - a dependency lock got added to the project and I didn't realize when I made the patch releases for `1.1.2`, so the plugin is carrying the `1.1.2` dependencies instead of the correct versions.

I've done a `v1.1.2-5.1` release so we at least have a fixed version for the latest release of `1.1.2`. 

FWIW, if I can get this work merged and released, we'll have everything this plugin does in the core plugin and I'll be able to deprecate this guy:

https://github.com/JetBrains/kotlin/pull/1042
