### ISSUE TITLE
Warning on kotlin 1.3.70

### ISSUE THREAD

**Issue by mattbroekhuis** [nebula-plugins/nebula-kotlin-plugin#37]
`
plugins {
    id 'nebula.kotlin' version '1.3.70'
`

`The 'org.jetbrains.kotlin.platform.*' plugins are deprecated and will no longer be available in Kotlin 1.4.
Please migrate the project to the 'org.jetbrains.kotlin.multiplatform' plugin.
See: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html`

**Comment by DanielThomas** [comment]
Weird to deprecate something in favor of something still considered experimental in 1.2 and 1.3. We could maybe have `nebula.kotlin` apply the multi-project plugin with a `jvm` target.

I'd hoped to be able to retire this plugin eventually, having it replaced with core features in the upstream plugin. I'll take a look at see how we're doing on parity now.

**Comment by DanielThomas** [comment]
I finally got a chance to take a look at the multiplatform plugin. It supports all of the ergonomic features we had such as JVM targets and library version management and is a complete migration from the existing plugin. We'll continue to release 1.x releases of this plugin but will retire it otherwise and recommend migrating to  the multiplatform plugin
