### ISSUE TITLE
If you do not provide version for other kotlin dependencies, pom.xml generation is incorrect

### ISSUE THREAD

**Issue by apatrida** [nebula-plugins/nebula-kotlin-plugin#4]
When doing something like the sample says:

```
dependencies {
    compile 'org.jetbrains.kotlin:kotlin-reflect'
}
```

But then you use the maven publishing plugin to generate a `pom.xml`, the dependency is missing its version number and the `pom.xml` causes the associated artifact to be invalid (i.e. you can publish to Maven Central but then no one can use the dependency, you get really odd errors and this becomes a "mystery bug").  Adding specific versions to all dependencies resolves this issue.

**Comment by DanielThomas** [comment]
@apatrida yeah, that's a gap in Gradle's publishing. They take the requested, rather than target (resolved) versions for first order dependencies. So the result of conflict resolution and resolution strategies aren't reflected, and dynamic version constraints get published as-is.

Our `nebula.maven-resolved` and `nebula.ivy-resolved` plugins provide a general purpose fix for that, just apply them to the project to get the expected result:

https://github.com/nebula-plugins/nebula-publishing-plugin#nebulamaven-resolved

**Comment by apatrida** [comment]
thanks @DanielThomas

**Comment by apatrida** [comment]
current plugin name is actually `nebula.maven-resolved-dependencies`
